version: '3'

services:
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_HOST=127.0.0.1
    ports:
      - "127.0.0.1:3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      -  ./.mysql:/var/lib/mysql:rw


  postgresql:
    image: postgres
    restart: always
    volumes:
      - ./.db:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  web:
    build: .
    container_name: contacts-api
    volumes:
        - .:/code
    ports:
        - 8000:8000
    depends_on:
        - mysql
        - postgresql
    environment:
        - ENVIRONMENT=DEVELOPMENT


